-- Versioned, reviewed course releases for the React Native learning core.
--
-- Existing Flutter curriculum rows remain untouched. A React Native learner
-- reads only a course explicitly published through this release layer. Draft
-- manifests, unreviewed content, and any exercise with unresolved rights stay
-- unavailable to the client by database policy as well as by app behaviour.

create table if not exists public.course_releases (
    id uuid primary key default gen_random_uuid(),
    course_key text not null
        check (course_key ~ '^[a-z][a-z0-9-]{2,79}$'),
    content_version text not null
        check (content_version ~ '^[0-9]+\.[0-9]+\.[0-9]+(-[a-z0-9.]+)?$'),
    target_language_code text not null
        check (target_language_code ~ '^[a-z]{2,3}(-[A-Z]{2})?$'),
    interface_locale text not null
        check (interface_locale ~ '^[a-z]{2,3}(-[A-Z]{2})?$'),
    title text not null check (char_length(title) between 1 and 160),
    publication_state text not null default 'draft'
        check (publication_state in ('draft', 'published', 'revoked')),
    manifest_checksum text not null
        check (manifest_checksum ~ '^[a-f0-9]{64}$'),
    manifest_uri text not null check (char_length(manifest_uri) between 1 and 500),
    learning_design_approval_ref text,
    native_language_approval_ref text,
    rights_approval_ref text,
    rollback_release_id uuid references public.course_releases(id),
    published_at timestamptz,
    revoked_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (course_key, content_version),
    check (
        publication_state <> 'published'
        or (
            published_at is not null
            and nullif(trim(learning_design_approval_ref), '') is not null
            and nullif(trim(native_language_approval_ref), '') is not null
            and nullif(trim(rights_approval_ref), '') is not null
        )
    ),
    check (publication_state <> 'revoked' or revoked_at is not null)
);

create table if not exists public.course_release_units (
    course_release_id uuid not null references public.course_releases(id) on delete cascade,
    unit_id text not null references public.units(id) on delete restrict,
    order_index integer not null check (order_index >= 0),
    primary key (course_release_id, unit_id),
    unique (course_release_id, order_index)
);

-- Answer material is deliberately stored as reviewed content rather than
-- generated by a client. The server uses it to decide practice completion;
-- the learner's raw response is never persisted by the function below.
create table if not exists public.lesson_exercises (
    id text primary key check (id ~ '^[a-z][a-z0-9_-]{2,79}$'),
    course_release_id uuid not null references public.course_releases(id) on delete cascade,
    lesson_id text not null references public.lessons(id) on delete cascade,
    flashcard_id text references public.flashcards(id) on delete set null,
    order_index integer not null check (order_index >= 0),
    exercise_type text not null
        check (exercise_type in ('recognition', 'typed_recall', 'guided_writing')),
    prompt text not null check (char_length(prompt) between 1 and 600),
    accepted_answers jsonb not null
        check (jsonb_typeof(accepted_answers) = 'array' and jsonb_array_length(accepted_answers) > 0),
    distractors jsonb not null default '[]'::jsonb
        check (jsonb_typeof(distractors) = 'array'),
    hint text not null check (char_length(hint) between 1 and 400),
    remediation text not null check (char_length(remediation) between 1 and 500),
    outcome_refs text[] not null default '{}'::text[]
        check (cardinality(outcome_refs) > 0),
    source_provider text not null check (char_length(source_provider) between 1 and 120),
    source_reference text not null check (char_length(source_reference) between 1 and 240),
    source_licence text not null check (char_length(source_licence) between 1 and 160),
    source_attribution text not null check (char_length(source_attribution) between 1 and 500),
    rights_status text not null check (rights_status in ('pending', 'cleared', 'rejected')),
    learning_design_approval_ref text,
    native_language_approval_ref text,
    rights_approval_ref text,
    is_required boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (course_release_id, lesson_id, order_index),
    check (
        exercise_type <> 'recognition'
        or jsonb_array_length(distractors) >= 2
    )
);

create index if not exists course_releases_published_language_idx
    on public.course_releases (target_language_code, interface_locale, content_version)
    where publication_state = 'published';
create index if not exists course_release_units_release_order_idx
    on public.course_release_units (course_release_id, order_index);
create index if not exists lesson_exercises_release_lesson_order_idx
    on public.lesson_exercises (course_release_id, lesson_id, order_index);

drop trigger if exists course_releases_set_updated_at on public.course_releases;
create trigger course_releases_set_updated_at
before update on public.course_releases
for each row execute function public.set_updated_at();

drop trigger if exists lesson_exercises_set_updated_at on public.lesson_exercises;
create trigger lesson_exercises_set_updated_at
before update on public.lesson_exercises
for each row execute function public.set_updated_at();

-- A release cannot be promoted just by changing a status label. The source
-- approval references, reviewed unit rows, and reviewed exercises must all be
-- in place first. This trigger is intentionally only a release gate; the
-- content JSON contract remains the authoring source of truth.
create or replace function public.assert_course_release_publishable()
returns trigger
language plpgsql
set search_path = public
as $$
begin
    if new.publication_state <> 'published' then
        return new;
    end if;

    if not exists (
        select 1
        from public.course_release_units map
        join public.units unit on unit.id = map.unit_id
        where map.course_release_id = new.id
          and unit.is_reviewed = true
    ) then
        raise exception 'Published course releases require at least one reviewed unit';
    end if;

    if exists (
        select 1
        from public.course_release_units map
        join public.units unit on unit.id = map.unit_id
        where map.course_release_id = new.id
          and unit.is_reviewed = false
    ) then
        raise exception 'Published course releases cannot include unreviewed units';
    end if;

    if not exists (
        select 1 from public.lesson_exercises exercise
        where exercise.course_release_id = new.id
    ) then
        raise exception 'Published course releases require reviewed exercises';
    end if;

    if exists (
        select 1
        from public.course_release_units map
        join public.lessons lesson on lesson.unit_id = map.unit_id
        where map.course_release_id = new.id
          and not exists (
              select 1 from public.lesson_exercises exercise
              where exercise.course_release_id = new.id
                and exercise.lesson_id = lesson.id
          )
    ) then
        raise exception 'Published course releases require reviewed exercises for every mapped lesson';
    end if;

    if exists (
        select 1
        from public.lesson_exercises exercise
        where exercise.course_release_id = new.id
          and not exists (
              select 1
              from public.course_release_units map
              join public.lessons lesson on lesson.unit_id = map.unit_id
              where map.course_release_id = new.id
                and lesson.id = exercise.lesson_id
          )
    ) then
        raise exception 'Published exercises must belong to a lesson mapped into the same release';
    end if;

    if exists (
        select 1 from public.lesson_exercises exercise
        where exercise.course_release_id = new.id
          and (
              exercise.rights_status <> 'cleared'
              or nullif(trim(exercise.learning_design_approval_ref), '') is null
              or nullif(trim(exercise.native_language_approval_ref), '') is null
              or nullif(trim(exercise.rights_approval_ref), '') is null
          )
    ) then
        raise exception 'Published course releases require cleared rights and reviewer evidence for every exercise';
    end if;

    return new;
end;
$$;

drop trigger if exists course_releases_publish_gate on public.course_releases;
create trigger course_releases_publish_gate
before insert or update of publication_state on public.course_releases
for each row execute function public.assert_course_release_publishable();

-- A published release is an evidence record, not a mutable draft. It can only
-- transition to revoked without altering the content identity or approvals.
-- New content requires a new versioned release row.
create or replace function public.prevent_published_course_release_mutation()
returns trigger
language plpgsql
set search_path = public
as $$
begin
    if tg_op = 'DELETE' then
        if old.publication_state in ('published', 'revoked') then
            raise exception 'Published or revoked course releases cannot be deleted';
        end if;
        return old;
    end if;

    if old.publication_state = 'revoked' then
        raise exception 'Revoked course releases cannot be changed';
    end if;

    if old.publication_state = 'published' then
        if new.publication_state <> 'revoked'
           or new.course_key is distinct from old.course_key
           or new.content_version is distinct from old.content_version
           or new.target_language_code is distinct from old.target_language_code
           or new.interface_locale is distinct from old.interface_locale
           or new.title is distinct from old.title
           or new.manifest_checksum is distinct from old.manifest_checksum
           or new.manifest_uri is distinct from old.manifest_uri
           or new.learning_design_approval_ref is distinct from old.learning_design_approval_ref
           or new.native_language_approval_ref is distinct from old.native_language_approval_ref
           or new.rights_approval_ref is distinct from old.rights_approval_ref
           or new.rollback_release_id is distinct from old.rollback_release_id
           or new.published_at is distinct from old.published_at
           or new.revoked_at is null then
            raise exception 'Published course releases may only be revoked without content changes';
        end if;
    end if;

    return new;
end;
$$;

create or replace function public.prevent_published_course_release_membership_mutation()
returns trigger
language plpgsql
set search_path = public
as $$
declare
    v_release_id uuid := case when tg_op = 'DELETE' then old.course_release_id else new.course_release_id end;
begin
    if exists (
        select 1 from public.course_releases release
        where release.id = v_release_id
          and release.publication_state in ('published', 'revoked')
    ) then
        raise exception 'Published or revoked course release membership cannot be changed';
    end if;
    if tg_op = 'DELETE' then
        return old;
    end if;
    return new;
end;
$$;

create or replace function public.prevent_published_lesson_exercise_mutation()
returns trigger
language plpgsql
set search_path = public
as $$
declare
    v_release_id uuid := case when tg_op = 'DELETE' then old.course_release_id else new.course_release_id end;
begin
    if exists (
        select 1 from public.course_releases release
        where release.id = v_release_id
          and release.publication_state in ('published', 'revoked')
    ) then
        raise exception 'Published or revoked lesson exercises cannot be changed';
    end if;
    if tg_op = 'DELETE' then
        return old;
    end if;
    return new;
end;
$$;

drop trigger if exists course_releases_immutable on public.course_releases;
create trigger course_releases_immutable
before update or delete on public.course_releases
for each row execute function public.prevent_published_course_release_mutation();

drop trigger if exists course_release_units_immutable on public.course_release_units;
create trigger course_release_units_immutable
before insert or update or delete on public.course_release_units
for each row execute function public.prevent_published_course_release_membership_mutation();

drop trigger if exists lesson_exercises_immutable on public.lesson_exercises;
create trigger lesson_exercises_immutable
before insert or update or delete on public.lesson_exercises
for each row execute function public.prevent_published_lesson_exercise_mutation();

create table if not exists public.lesson_attempts (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references auth.users(id) on delete cascade,
    course_release_id uuid not null references public.course_releases(id) on delete restrict,
    lesson_id text not null references public.lessons(id) on delete restrict,
    content_version text not null,
    started_at timestamptz not null default now(),
    completed_at timestamptz,
    unique (id, user_id)
);

create unique index if not exists lesson_attempts_one_open_attempt_idx
    on public.lesson_attempts (user_id, course_release_id, lesson_id, content_version)
    where completed_at is null;

create table if not exists public.lesson_exercise_attempts (
    lesson_attempt_id uuid not null references public.lesson_attempts(id) on delete cascade,
    exercise_id text not null references public.lesson_exercises(id) on delete restrict,
    is_correct boolean not null,
    submitted_at timestamptz not null default now(),
    primary key (lesson_attempt_id, exercise_id)
);

create index if not exists lesson_attempts_user_lesson_idx
    on public.lesson_attempts (user_id, lesson_id, completed_at desc);

alter table public.course_releases enable row level security;
alter table public.course_release_units enable row level security;
alter table public.lesson_exercises enable row level security;
alter table public.lesson_attempts enable row level security;
alter table public.lesson_exercise_attempts enable row level security;

drop policy if exists "read published course releases" on public.course_releases;
create policy "read published course releases" on public.course_releases
    for select to anon, authenticated
    using (publication_state = 'published' and revoked_at is null);

drop policy if exists "read units in published course releases" on public.course_release_units;
create policy "read units in published course releases" on public.course_release_units
    for select to anon, authenticated
    using (
        exists (
            select 1 from public.course_releases release
            where release.id = course_release_units.course_release_id
              and release.publication_state = 'published'
              and release.revoked_at is null
        )
    );

drop policy if exists "read exercises in published course releases" on public.lesson_exercises;
create policy "read exercises in published course releases" on public.lesson_exercises
    for select to anon, authenticated
    using (
        exists (
            select 1 from public.course_releases release
            where release.id = lesson_exercises.course_release_id
              and release.publication_state = 'published'
              and release.revoked_at is null
        )
    );

drop policy if exists "learners read own lesson attempts" on public.lesson_attempts;
create policy "learners read own lesson attempts" on public.lesson_attempts
    for select to authenticated using (user_id = auth.uid());

drop policy if exists "learners read own exercise attempts" on public.lesson_exercise_attempts;
create policy "learners read own exercise attempts" on public.lesson_exercise_attempts
    for select to authenticated
    using (
        exists (
            select 1 from public.lesson_attempts attempt
            where attempt.id = lesson_exercise_attempts.lesson_attempt_id
              and attempt.user_id = auth.uid()
        )
    );

revoke all on table public.course_releases, public.course_release_units,
    public.lesson_exercises, public.lesson_attempts, public.lesson_exercise_attempts
    from anon, authenticated;
grant select on table public.course_releases, public.course_release_units,
    public.lesson_exercises to anon, authenticated;
grant select on table public.lesson_attempts, public.lesson_exercise_attempts to authenticated;

-- Record a response without persisting its raw text. The server obtains the
-- expected answers from the published release, keeps one active attempt per
-- learner, and returns only the result needed for the UI.
create or replace function public.record_lesson_exercise_response(
    p_lesson_id text,
    p_exercise_id text,
    p_language_code text,
    p_content_version text,
    p_response text
)
returns table (
    is_correct boolean,
    lesson_complete boolean,
    completed_required_exercises integer,
    total_required_exercises integer
)
language plpgsql
security definer
set search_path = public
as $$
declare
    v_user uuid := auth.uid();
    v_release_id uuid;
    v_attempt_id uuid;
    v_expected_answers jsonb;
    v_is_correct boolean;
    v_completed integer;
    v_total integer;
begin
    if v_user is null then
        raise exception 'Authentication required' using errcode = '28000';
    end if;
    if p_response is null or char_length(p_response) > 2000 then
        raise exception 'Invalid practice response' using errcode = '22023';
    end if;

    select release.id
    into v_release_id
    from public.course_releases release
    join public.course_release_units map on map.course_release_id = release.id
    join public.lessons lesson on lesson.unit_id = map.unit_id
    where release.publication_state = 'published'
      and release.revoked_at is null
      and release.target_language_code = p_language_code
      and release.content_version = p_content_version
      and lesson.id = p_lesson_id
    limit 1;

    if v_release_id is null then
        raise exception 'The selected lesson is not in a current published release' using errcode = '22023';
    end if;

    select exercise.accepted_answers
    into v_expected_answers
    from public.lesson_exercises exercise
    where exercise.id = p_exercise_id
      and exercise.course_release_id = v_release_id
      and exercise.lesson_id = p_lesson_id;

    if v_expected_answers is null then
        raise exception 'The selected exercise is not in the published lesson' using errcode = '22023';
    end if;

    select exists (
        select 1
        from jsonb_array_elements_text(v_expected_answers) as answer(value)
        where lower(regexp_replace(trim(answer.value), '[[:space:]]+', ' ', 'g'))
            = lower(regexp_replace(trim(p_response), '[[:space:]]+', ' ', 'g'))
    ) into v_is_correct;

    select attempt.id
    into v_attempt_id
    from public.lesson_attempts attempt
    where attempt.user_id = v_user
      and attempt.course_release_id = v_release_id
      and attempt.lesson_id = p_lesson_id
      and attempt.content_version = p_content_version
      and attempt.completed_at is null
    order by attempt.started_at desc
    limit 1
    for update;

    if v_attempt_id is null then
        insert into public.lesson_attempts
            (user_id, course_release_id, lesson_id, content_version)
        values (v_user, v_release_id, p_lesson_id, p_content_version)
        returning id into v_attempt_id;
    end if;

    insert into public.lesson_exercise_attempts
        (lesson_attempt_id, exercise_id, is_correct)
    values (v_attempt_id, p_exercise_id, v_is_correct)
    on conflict (lesson_attempt_id, exercise_id) do update
    set is_correct = public.lesson_exercise_attempts.is_correct or excluded.is_correct,
        submitted_at = now();

    select count(*) into v_total
    from public.lesson_exercises exercise
    where exercise.course_release_id = v_release_id
      and exercise.lesson_id = p_lesson_id
      and exercise.is_required = true;

    select count(*) into v_completed
    from public.lesson_exercise_attempts attempt
    join public.lesson_exercises exercise on exercise.id = attempt.exercise_id
    where attempt.lesson_attempt_id = v_attempt_id
      and attempt.is_correct = true
      and exercise.is_required = true;

    if v_total > 0 and v_completed >= v_total then
        update public.lesson_attempts
        set completed_at = coalesce(completed_at, now())
        where id = v_attempt_id;
    end if;

    return query select v_is_correct, v_total > 0 and v_completed >= v_total, v_completed, v_total;
end;
$$;

-- Record completion only after the server has a completed exercise attempt in
-- the exact current course version. This is additive so the Flutter fallback
-- keeps using its existing completion RPC until it is migrated deliberately.
create or replace function public.complete_published_lesson(
    p_lesson_id text,
    p_language_code text,
    p_content_version text
)
returns table (attempts integer)
language plpgsql
security definer
set search_path = public
as $$
declare
    v_user uuid := auth.uid();
    v_release_id uuid;
    v_attempts integer;
begin
    if v_user is null then
        raise exception 'Authentication required' using errcode = '28000';
    end if;

    select release.id
    into v_release_id
    from public.course_releases release
    join public.course_release_units map on map.course_release_id = release.id
    join public.lessons lesson on lesson.unit_id = map.unit_id
    where release.publication_state = 'published'
      and release.revoked_at is null
      and release.target_language_code = p_language_code
      and release.content_version = p_content_version
      and lesson.id = p_lesson_id
    limit 1;

    if v_release_id is null or not exists (
        select 1 from public.lesson_attempts attempt
        where attempt.user_id = v_user
          and attempt.course_release_id = v_release_id
          and attempt.lesson_id = p_lesson_id
          and attempt.content_version = p_content_version
          and attempt.completed_at is not null
    ) then
        raise exception 'Complete each required published exercise before recording this lesson' using errcode = '22023';
    end if;

    insert into public.lesson_progress (user_id, lesson_id, language_code)
    values (v_user, p_lesson_id, p_language_code)
    on conflict (user_id, lesson_id) do update
    set attempts = public.lesson_progress.attempts + 1,
        last_completed_at = now()
    returning lesson_progress.attempts into v_attempts;

    return query select v_attempts;
end;
$$;

-- SRS scheduling is server-authoritative for published release cards. The
-- learner supplies a rating, but cannot write intervals, repetitions, or due
-- timestamps directly through this RN contract.
create or replace function public.record_card_review(
    p_card_id text,
    p_language_code text,
    p_rating text
)
returns table (
    next_review_at timestamptz,
    interval_days integer,
    repetitions integer,
    efactor numeric
)
language plpgsql
security definer
set search_path = public
as $$
declare
    v_user uuid := auth.uid();
    v_interval integer := 0;
    v_repetitions integer := 0;
    v_efactor numeric := 2.50;
    v_next_review_at timestamptz;
begin
    if v_user is null then
        raise exception 'Authentication required' using errcode = '28000';
    end if;
    if p_rating not in ('again', 'hard', 'good', 'easy') then
        raise exception 'Invalid review rating' using errcode = '22023';
    end if;
    if not exists (
        select 1
        from public.course_releases release
        join public.course_release_units map on map.course_release_id = release.id
        join public.lessons lesson on lesson.unit_id = map.unit_id
        join public.flashcards card on card.lesson_id = lesson.id
        where release.publication_state = 'published'
          and release.revoked_at is null
          and release.target_language_code = p_language_code
          and card.id = p_card_id
    ) then
        raise exception 'The selected card is not in a current published release' using errcode = '22023';
    end if;

    select review.interval, review.repetitions, review.efactor
    into v_interval, v_repetitions, v_efactor
    from public.card_reviews review
    where review.user_id = v_user
      and review.card_id = p_card_id
      and review.language_key = p_language_code
    for update;

    v_interval := coalesce(v_interval, 0);
    v_repetitions := coalesce(v_repetitions, 0);
    v_efactor := coalesce(v_efactor, 2.50);

    if p_rating = 'again' then
        v_repetitions := 0;
        v_interval := 0;
        v_efactor := greatest(1.30, v_efactor - 0.20);
        v_next_review_at := now() + interval '10 minutes';
    else
        v_repetitions := v_repetitions + 1;
        v_efactor := least(
            2.80,
            greatest(1.30, v_efactor + case p_rating when 'hard' then -0.15 when 'easy' then 0.15 else 0 end)
        );
        if v_repetitions = 1 then
            v_interval := case p_rating when 'hard' then 1 when 'easy' then 2 else 1 end;
        elsif v_repetitions = 2 then
            v_interval := case p_rating when 'hard' then 2 when 'easy' then 5 else 3 end;
        else
            v_interval := greatest(
                1,
                ceil(v_interval * (v_efactor + case p_rating when 'hard' then -0.15 when 'easy' then 0.15 else 0 end))::integer
            );
        end if;
        v_next_review_at := now() + make_interval(days => v_interval);
    end if;

    insert into public.card_reviews
        (user_id, card_id, language_key, interval, repetitions, efactor, next_review_at)
    values (v_user, p_card_id, p_language_code, v_interval, v_repetitions, v_efactor, v_next_review_at)
    on conflict (user_id, card_id, language_key) do update
    set interval = excluded.interval,
        repetitions = excluded.repetitions,
        efactor = excluded.efactor,
        next_review_at = excluded.next_review_at,
        updated_at = now();

    return query select v_next_review_at, v_interval, v_repetitions, v_efactor;
end;
$$;

revoke all on function public.assert_course_release_publishable() from public;
revoke all on function public.prevent_published_course_release_mutation() from public;
revoke all on function public.prevent_published_course_release_membership_mutation() from public;
revoke all on function public.prevent_published_lesson_exercise_mutation() from public;
revoke all on function public.record_lesson_exercise_response(text, text, text, text, text)
    from public, anon, authenticated, service_role;
revoke all on function public.complete_published_lesson(text, text, text)
    from public, anon, authenticated, service_role;
revoke all on function public.record_card_review(text, text, text)
    from public, anon, authenticated, service_role;
grant execute on function public.record_lesson_exercise_response(text, text, text, text, text)
    to authenticated;
grant execute on function public.complete_published_lesson(text, text, text)
    to authenticated;
grant execute on function public.record_card_review(text, text, text)
    to authenticated;
